/* Shop Studio Pro v11.6 — stabilization layer: Passport workflow, Print Studio Pro, Advanced PDF Studio */
(()=>{
'use strict';
const $=id=>document.getElementById(id);
const clamp=(v,a,b)=>Math.max(a,Math.min(b,v));
const mm2px=(mm,dpi=300)=>Math.max(1,Math.round(mm/25.4*dpi));
const blobOf=(c,t='image/png',q=.95)=>new Promise((res,rej)=>c.toBlob(b=>b?res(b):rej(new Error('Canvas export failed')),t,q));
const imgFromFile=f=>new Promise((res,rej)=>{const u=URL.createObjectURL(f),im=new Image();im.onload=()=>{URL.revokeObjectURL(u);res(im)};im.onerror=e=>{URL.revokeObjectURL(u);rej(e)};im.src=u});
const imgFromCanvas=c=>new Promise((res,rej)=>{const im=new Image();im.onload=()=>res(im);im.onerror=rej;im.src=c.toDataURL('image/png')});
const download=(blob,name)=>{const a=document.createElement('a'),u=URL.createObjectURL(blob);a.href=u;a.download=window.shopAutoFilename?window.shopAutoFilename(name):name;document.body.appendChild(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(u),1500)};
const cloneCanvas=c=>{const n=document.createElement('canvas');n.width=c.width;n.height=c.height;n.getContext('2d').drawImage(c,0,0);return n};
const pdfjs=async()=>{const m=await import('https://cdnjs.cloudflare.com/ajax/libs/pdf.js/4.10.38/pdf.min.mjs');m.GlobalWorkerOptions.workerSrc='https://cdnjs.cloudflare.com/ajax/libs/pdf.js/4.10.38/pdf.worker.min.mjs';return m};
const S=window.state||{};

function removeSmartCrop(){
  document.querySelectorAll('button,label,.mini-btn,.ghost-btn,.primary-btn').forEach(el=>{
    const t=(el.textContent||'').trim(); if(/^smart\s*crop$/i.test(t)||/smart\s+auto\s*crop/i.test(t)) el.remove();
  });
}

/* -------- Passport Photo: keep sheet inside Passport section -------- */
function installPassportSheet(){
  const sec=$('photo'),btn=$('makePassportSheet'); if(!sec||!btn)return;
  let panel=$('passportSheetV116');
  if(!panel){
    panel=document.createElement('div');panel.id='passportSheetV116';panel.className='passport-sheet-v116';panel.hidden=true;
    panel.innerHTML=`
      <div class="workspace-head passport-sheet-head"><div><span class="eyebrow">PASSPORT PRINT SHEET</span><h3>Sheet Preview & Print Settings</h3></div><div class="button-row"><button class="ghost-btn" id="passportSheetClose">Close Preview</button></div></div>
      <div class="compact-controls passport-sheet-controls">
        <label>Paper<select id="ps116Paper"><option value="6x4">6×4</option><option value="a4">A4</option></select></label>
        <label>Orientation<select id="ps116Orientation"><option value="landscape">Landscape</option><option value="portrait">Portrait</option></select></label>
        <label>Copies<input id="ps116Copies" type="number" min="1" max="50" value="8"></label>
        <label>Margin (mm)<input id="ps116Margin" type="number" min="0" max="30" step="0.5" value="3"></label>
        <label>Photo Gap (mm)<input id="ps116Gap" type="number" min="0" max="20" step="0.5" value="4.5"></label>
        <label>DPI<select id="ps116Dpi"><option value="300" selected>300</option><option value="600">600</option></select></label>
        <label>Border<select id="ps116Border"><option value="0">None</option><option value="1">1 px</option><option value="2" selected>2 px</option><option value="3">3 px</option></select></label>
        <label>Cut Lines<select id="ps116Cut"><option value="yes" selected>On</option><option value="no">Off</option></select></label>
      </div>
      <div class="canvas-wrap passport-sheet-canvas-wrap"><canvas id="passportSheetCanvasV116"></canvas></div>
      <div class="status-inline" id="passportSheetStatusV116">Change any option to regenerate automatically.</div>
      <div class="workspace-actions"><button class="primary-btn" id="passportSheetRegenV116">Regenerate</button><button class="ghost-btn" id="passportSheetPngV116">PNG</button><button class="ghost-btn" id="passportSheetPdfV116">PDF</button><button class="ghost-btn" id="passportSheetPrintV116">Print</button></div>`;
    sec.querySelector('.panel')?.appendChild(panel);
  }
  const old=btn.cloneNode(true);btn.replaceWith(old);
  const srcCanvas=$('photoCanvas');
  function syncBase(){
    $('ps116Paper').value=$('passportPaper')?.value||'6x4';
    $('ps116Copies').value=$('passportCopies')?.value||8;
    $('ps116Border').value=$('passportBorder')?.value||2;
    $('ps116Cut').value=$('passportCutLines')?.value||'yes';
    const pm=$('passportMargin');if(pm)$('ps116Margin').value=pm.value;
    const pg=$('passportGap');if(pg)$('ps116Gap').value=pg.value;
  }
  function draw(){
    if(!srcCanvas||!srcCanvas.width){$('passportSheetStatusV116').textContent='Upload and prepare a passport photo first.';return;}
    const dpi=+$('ps116Dpi').value||300,paper=$('ps116Paper').value,ori=$('ps116Orientation').value;
    let W=paper==='a4'?mm2px(210,dpi):6*dpi,H=paper==='a4'?mm2px(297,dpi):4*dpi;if(ori==='landscape'&&H>W)[W,H]=[H,W];if(ori==='portrait'&&W>H)[W,H]=[H,W];
    const ratio=$('passportRatio')?.value||'0.7777778';let photoW=mm2px(ratio==='0.8'?40:35,dpi),photoH=mm2px(ratio==='0.8'?50:45,dpi);
    const count=Math.max(1,+$('ps116Copies').value||8),margin=mm2px(+$('ps116Margin').value||0,dpi),gap=mm2px(+$('ps116Gap').value||0,dpi);
    const availW=Math.max(1,W-margin*2),availH=Math.max(1,H-margin*2);
    let best=null;for(let cols=1;cols<=count;cols++){const rows=Math.ceil(count/cols),gw=cols*photoW+(cols-1)*gap,gh=rows*photoH+(rows-1)*gap;if(gw<=availW&&gh<=availH){const waste=(availW-gw)+(availH-gh);if(!best||waste<best.waste)best={cols,rows,gw,gh,waste}}}
    if(!best){const cols=Math.ceil(Math.sqrt(count*availW/availH)),rows=Math.ceil(count/cols),maxPW=(availW-(cols-1)*gap)/cols,maxPH=(availH-(rows-1)*gap)/rows,scale=Math.min(maxPW/photoW,maxPH/photoH);photoW=Math.max(1,Math.floor(photoW*scale));photoH=Math.max(1,Math.floor(photoH*scale));best={cols,rows,gw:cols*photoW+(cols-1)*gap,gh:rows*photoH+(rows-1)*gap};}
    const c=$('passportSheetCanvasV116'),ctx=c.getContext('2d');c.width=W;c.height=H;ctx.fillStyle='#fff';ctx.fillRect(0,0,W,H);ctx.imageSmoothingEnabled=true;ctx.imageSmoothingQuality='high';
    const sx=(W-best.gw)/2,sy=(H-best.gh)/2,border=+$('ps116Border').value||0,cut=$('ps116Cut').value==='yes';
    for(let i=0;i<count;i++){const col=i%best.cols,row=Math.floor(i/best.cols),x=Math.round(sx+col*(photoW+gap)),y=Math.round(sy+row*(photoH+gap));ctx.drawImage(srcCanvas,0,0,srcCanvas.width,srcCanvas.height,x,y,photoW,photoH);if(border){ctx.strokeStyle='#111';ctx.lineWidth=border;ctx.strokeRect(x+.5,y+.5,photoW-1,photoH-1)}if(cut){ctx.save();ctx.strokeStyle='rgba(0,0,0,.55)';ctx.lineWidth=1;ctx.setLineDash([]);const m=Math.max(8,Math.round(dpi/25)),o=Math.max(3,Math.round(dpi/75));ctx.beginPath();ctx.moveTo(x-o-m,y-o);ctx.lineTo(x-o,y-o);ctx.lineTo(x-o,y-o-m);ctx.moveTo(x+photoW+o+m,y-o);ctx.lineTo(x+photoW+o,y-o);ctx.lineTo(x+photoW+o,y-o-m);ctx.moveTo(x-o-m,y+photoH+o);ctx.lineTo(x-o,y+photoH+o);ctx.lineTo(x-o,y+photoH+o+m);ctx.moveTo(x+photoW+o+m,y+photoH+o);ctx.lineTo(x+photoW+o,y+photoH+o);ctx.lineTo(x+photoW+o,y+photoH+o+m);ctx.stroke();ctx.restore()}}
    $('passportSheetStatusV116').textContent=`${count} photo(s) • ${paper.toUpperCase()} ${ori} • margin ${$('ps116Margin').value} mm • gap ${$('ps116Gap').value} mm • ${dpi} DPI`;
  }
  old.addEventListener('click',e=>{e.preventDefault();syncBase();panel.hidden=false;draw();panel.scrollIntoView({behavior:'smooth',block:'start'})});
  $('passportSheetClose').onclick=()=>panel.hidden=true;
  $('passportSheetRegenV116').onclick=draw;
  panel.querySelectorAll('input,select').forEach(x=>x.addEventListener('input',draw));
  $('passportSheetPngV116').onclick=async()=>{draw();download(await blobOf($('passportSheetCanvasV116'),'image/png'),'passport-sheet.png')};
  $('passportSheetPdfV116').onclick=async()=>{draw();if(!window.PDFLib)return;const c=$('passportSheetCanvasV116'),doc=await PDFLib.PDFDocument.create(),im=await doc.embedPng(await (await blobOf(c,'image/png')).arrayBuffer()),p=doc.addPage([im.width,im.height]);p.drawImage(im,{x:0,y:0,width:im.width,height:im.height});download(new Blob([await doc.save()],{type:'application/pdf'}),'passport-sheet.pdf')};
  $('passportSheetPrintV116').onclick=()=>{draw();const u=$('passportSheetCanvasV116').toDataURL('image/png'),w=open('','_blank');if(!w)return;w.document.write(`<html><head><title>Passport Sheet</title><style>@page{margin:0}body{margin:0;display:grid;place-items:center}img{max-width:100%;max-height:100vh}</style></head><body><img src="${u}" onload="print();setTimeout(()=>close(),500)"></body></html>`);w.document.close()};
}

/* -------- Print Studio Pro: snap/alignment/templates -------- */
function installPrintStudioPro(){
  const sec=$('print'),wrap=$('printCanvasWrap'),canvas=$('printCanvas');if(!sec||!wrap||!canvas)return;
  // Disable previous overlays/controllers to avoid competing pointer handlers.
  ['printV111Layer','printInteractiveLayer','printEditor'].forEach(id=>{const n=$(id);if(n){n.style.display='none';n.style.pointerEvents='none'}});
  let bar=$('printV116Tools');if(!bar){bar=document.createElement('div');bar.id='printV116Tools';bar.className='print-v116-tools';bar.innerHTML=`<label class="upload-btn">Load Images<input id="printV116Images" type="file" accept="image/*" multiple hidden></label><label class="ghost-btn">Load PDF<input id="printV116Pdf" type="file" accept="application/pdf" hidden></label><label>Snap <input id="printV116Snap" type="checkbox" checked></label><label>Grid mm <input id="printV116Grid" type="number" value="2" min="0.5" step="0.5"></label><button class="ghost-btn" id="printV116AlignL">Align Left</button><button class="ghost-btn" id="printV116AlignC">Center X</button><button class="ghost-btn" id="printV116AlignT">Align Top</button><button class="ghost-btn" id="printV116CenterY">Center Y</button><button class="ghost-btn" id="printV116SaveTpl">Save Template</button><button class="ghost-btn" id="printV116LoadTpl">Load Template</button>`;sec.querySelector('.compact-controls')?.insertAdjacentElement('afterend',bar)}
  let layer=$('printV116Layer');if(!layer){layer=document.createElement('div');layer.id='printV116Layer';layer.className='print-v116-layer';wrap.appendChild(layer)}
  let sources=[],items=[],sel=new Set(),active=-1;
  const paper=()=>{const dpi=+($('printDpiV11')?.value||$('printDpi')?.value||300),p=$('printPaper')?.value||'6x4',o=$('printOrientation')?.value||'landscape';let w=p==='a4'?mm2px(210,dpi):6*dpi,h=p==='a4'?mm2px(297,dpi):4*dpi;if(o==='landscape'&&h>w)[w,h]=[h,w];if(o==='portrait'&&w>h)[w,h]=[h,w];return{w,h,dpi}};
  const snap=(v,axis)=>{if(!$('printV116Snap').checked)return v;const p=paper(),step=mm2px(+$('printV116Grid').value||2,p.dpi)/(axis==='x'?p.w:p.h);return Math.round(v/step)*step};
  function layout(){if(!sources.length)return;const {w,h,dpi}=paper(),n=Math.max(1,+$('printCount').value||sources.length),cols=Math.ceil(Math.sqrt(n*w/h)),rows=Math.ceil(n/cols),m=mm2px(+$('printMargin').value||4,dpi),g=mm2px(+($('printGapV11')?.value||$('printGap')?.value||3),dpi),cw=(w-2*m-(cols-1)*g)/cols,ch=(h-2*m-(rows-1)*g)/rows;items=[];for(let i=0;i<n;i++){const s=sources[i%sources.length];items.push({img:s.img,name:s.name,x:(m+(i%cols)*(cw+g))/w,y:(m+Math.floor(i/cols)*(ch+g))/h,w:cw/w,h:ch/h,crop:{x:0,y:0,w:1,h:1}})}sel=new Set([0]);active=0;draw()}
  function draw(){const {w,h}=paper(),ctx=canvas.getContext('2d');canvas.width=w;canvas.height=h;ctx.fillStyle='#fff';ctx.fillRect(0,0,w,h);ctx.imageSmoothingEnabled=true;ctx.imageSmoothingQuality='high';items.forEach(it=>{const r=it.crop;ctx.drawImage(it.img,r.x*it.img.width,r.y*it.img.height,r.w*it.img.width,r.h*it.img.height,it.x*w,it.y*h,it.w*w,it.h*h)});$('printEmpty')&&( $('printEmpty').style.display=items.length?'none':'');requestAnimationFrame(overlay)}
  function overlay(){const cr=canvas.getBoundingClientRect(),wr=wrap.getBoundingClientRect();layer.style.left=(cr.left-wr.left+wrap.scrollLeft)+'px';layer.style.top=(cr.top-wr.top+wrap.scrollTop)+'px';layer.style.width=cr.width+'px';layer.style.height=cr.height+'px';layer.innerHTML='';items.forEach((it,i)=>{const d=document.createElement('div');d.className='print-v116-item'+(sel.has(i)?' selected':'');Object.assign(d.style,{left:it.x*100+'%',top:it.y*100+'%',width:it.w*100+'%',height:it.h*100+'%'});d.dataset.i=i;['nw','n','ne','e','se','s','sw','w'].forEach(h=>{const q=document.createElement('i');q.className='print-v116-handle '+h;q.dataset.h=h;d.appendChild(q)});d.onpointerdown=e=>{e.preventDefault();e.stopPropagation();if(!e.ctrlKey&&!e.metaKey&&!sel.has(i))sel.clear();sel.add(i);active=i;overlay();const hnd=e.target.dataset.h||'move',base=items.map(x=>({...x})),sx=e.clientX,sy=e.clientY,cw=cr.width,ch=cr.height;const mv=ev=>{const dx=(ev.clientX-sx)/cw,dy=(ev.clientY-sy)/ch;sel.forEach(k=>{const b=base[k],n={...b};if(hnd==='move'){n.x=clamp(snap(b.x+dx,'x'),0,1-b.w);n.y=clamp(snap(b.y+dy,'y'),0,1-b.h)}else{const min=.02;if(hnd.includes('w')){const nx=clamp(snap(b.x+dx,'x'),0,b.x+b.w-min);n.w=b.w+(b.x-nx);n.x=nx}if(hnd.includes('e'))n.w=clamp(snap(b.w+dx,'x'),min,1-b.x);if(hnd.includes('n')){const ny=clamp(snap(b.y+dy,'y'),0,b.y+b.h-min);n.h=b.h+(b.y-ny);n.y=ny}if(hnd.includes('s'))n.h=clamp(snap(b.h+dy,'y'),min,1-b.y)}items[k]=n});draw()};const up=()=>{document.removeEventListener('pointermove',mv,true);document.removeEventListener('pointerup',up,true)};document.addEventListener('pointermove',mv,true);document.addEventListener('pointerup',up,true)};layer.appendChild(d)})}
  async function addFiles(files){for(const f of files){try{sources.push({img:await imgFromFile(f),name:f.name})}catch{}}layout()}
  $('printV116Images').onchange=e=>addFiles([...e.target.files]);
  $('printV116Pdf').onchange=async e=>{const f=e.target.files?.[0];if(!f)return;const m=await pdfjs(),pdf=await m.getDocument({data:new Uint8Array(await f.arrayBuffer())}).promise;for(let n=1;n<=pdf.numPages;n++){const p=await pdf.getPage(n),v=p.getViewport({scale:2}),c=document.createElement('canvas');c.width=Math.ceil(v.width);c.height=Math.ceil(v.height);await p.render({canvasContext:c.getContext('2d'),viewport:v}).promise;sources.push({img:await imgFromCanvas(c),name:`${f.name} p${n}`})}layout()};
  function align(type){if(!sel.size)return;const arr=[...sel].map(i=>items[i]);if(type==='l'){const x=Math.min(...arr.map(x=>x.x));sel.forEach(i=>items[i].x=x)}if(type==='cx')sel.forEach(i=>items[i].x=(1-items[i].w)/2);if(type==='t'){const y=Math.min(...arr.map(x=>x.y));sel.forEach(i=>items[i].y=y)}if(type==='cy')sel.forEach(i=>items[i].y=(1-items[i].h)/2);draw()}
  $('printV116AlignL').onclick=()=>align('l');$('printV116AlignC').onclick=()=>align('cx');$('printV116AlignT').onclick=()=>align('t');$('printV116CenterY').onclick=()=>align('cy');
  $('printV116SaveTpl').onclick=()=>{localStorage.setItem('shopstudio_print_template_v116',JSON.stringify({paper:$('printPaper').value,orientation:$('printOrientation').value,margin:$('printMargin').value,count:$('printCount').value,items:items.map(({x,y,w,h,crop})=>({x,y,w,h,crop}))}));alert('Print template saved on this device.')};
  $('printV116LoadTpl').onclick=()=>{let t;try{t=JSON.parse(localStorage.getItem('shopstudio_print_template_v116')||'null')}catch{}if(!t)return alert('No saved template yet.');$('printPaper').value=t.paper;$('printOrientation').value=t.orientation;$('printMargin').value=t.margin;$('printCount').value=t.count;if(sources.length&&t.items?.length){items=t.items.map((x,i)=>({...x,img:sources[i%sources.length].img,name:sources[i%sources.length].name}));draw()}else layout()};
  ['printCount','printPaper','printOrientation','printMargin','printGapV11','printDpiV11','printDpi'].forEach(id=>$(id)?.addEventListener('change',()=>sources.length&&layout()));
  const oldBuild=$('buildPrintSheet');if(oldBuild){const b=oldBuild.cloneNode(true);oldBuild.replaceWith(b);b.onclick=()=>sources.length?layout():$('printV116Images').click()}
  const oldPng=$('downloadPrintSheet');if(oldPng){const b=oldPng.cloneNode(true);oldPng.replaceWith(b);b.onclick=async()=>{if(!canvas.width)return;download(await blobOf(canvas,'image/png'),'print-layout.png')}}
  const oldPdf=$('downloadPrintSheetPdf');if(oldPdf){const b=oldPdf.cloneNode(true);oldPdf.replaceWith(b);b.onclick=async()=>{if(!window.PDFLib||!canvas.width)return;const doc=await PDFLib.PDFDocument.create(),im=await doc.embedPng(await (await blobOf(canvas,'image/png')).arrayBuffer()),p=doc.addPage([im.width,im.height]);p.drawImage(im,{x:0,y:0,width:im.width,height:im.height});download(new Blob([await doc.save()],{type:'application/pdf'}),'print-layout.pdf')}}
}

/* -------- Advanced PDF Studio v11.6 -------- */
function installPdfStudio(){
  const sec=$('pdf');if(!sec)return;
  $('pdfAdvancedV115')?.remove();$('openAdvancedPdfV115')?.closest('.utility-card')?.remove();
  let card=$('pdfV116Card');if(!card){card=document.createElement('div');card.id='pdfV116Card';card.className='utility-card';card.innerHTML='<h3>Advanced PDF Studio</h3><p class="muted">Crop, perspective, pages, enhance, print and export.</p><button class="primary-btn" id="openPdfV116">Open Studio</button>';sec.querySelector('.utility-grid')?.appendChild(card)}
  let panel=$('pdfStudioV116');if(!panel){panel=document.createElement('div');panel.id='pdfStudioV116';panel.className='pdf116 panel';panel.hidden=true;panel.innerHTML=`
  <div class="workspace-head"><div><span class="eyebrow">ADVANCED PDF STUDIO</span><h2>Professional PDF Workspace</h2></div><div class="button-row"><label class="upload-btn">Open PDF<input id="pdf116Open" type="file" accept="application/pdf" hidden></label><button class="ghost-btn" id="pdf116Undo">Undo</button><button class="ghost-btn" id="pdf116Redo">Redo</button><button class="ghost-btn" id="pdf116Pages">Show All Pages</button><button class="ghost-btn" id="pdf116Close">Close</button></div></div>
  <div class="pdf116-toolbar">
    <label>Apply To<select id="pdf116Scope"><option value="current">Current</option><option value="selected">Selected</option><option value="all">All</option><option value="even">Even</option><option value="odd">Odd</option></select></label>
    <button class="ghost-btn" id="pdf116SelAll">All</button><button class="ghost-btn" id="pdf116SelEven">Even</button><button class="ghost-btn" id="pdf116SelOdd">Odd</button><button class="ghost-btn" id="pdf116SelClear">Clear</button>
    <button class="ghost-btn" id="pdf116Crop">Crop</button><button class="ghost-btn" id="pdf116AutoCrop">Auto Detect</button><button class="ghost-btn" id="pdf116Perspective">Perspective Crop</button><button class="ghost-btn" id="pdf116Deskew">Auto Deskew / Orient</button><button class="ghost-btn" id="pdf116RemoveBgWhite" title="Remove the background from passport/photo PDF pages and replace it with pure white">Remove BG + White</button>
    <button class="ghost-btn" id="pdf116RotL">↶ Rotate</button><button class="ghost-btn" id="pdf116RotR">↷ Rotate</button><select id="pdf116Color"><option value="original">Original</option><option value="document">Document Enhance</option><option value="gray">Grayscale</option><option value="adaptive">Adaptive B&W</option></select>
    <button class="ghost-btn" id="pdf116Delete">Delete</button><button class="ghost-btn" id="pdf116Blank">Add Blank</button><label class="ghost-btn">Add PDF<input id="pdf116AddPdf" type="file" accept="application/pdf" hidden></label><label class="ghost-btn">Add Image<input id="pdf116AddImage" type="file" accept="image/*" multiple hidden></label><label class="ghost-btn">Replace Page<input id="pdf116Replace" type="file" accept="image/*,application/pdf" hidden></label><button class="ghost-btn" id="pdf116Scanner">Insert Scanner Page</button>
  </div>
  <div class="pdf116-body"><div class="pdf116-thumbs" id="pdf116Thumbs"></div><div class="pdf116-stage" id="pdf116Stage"><div class="pdf116-canvas-shell" id="pdf116Shell"><canvas id="pdf116Canvas"></canvas><div id="pdf116CropBox" class="pdf116-crop" hidden>${['nw','n','ne','e','se','s','sw','w'].map(h=>`<i class="${h}" data-h="${h}"></i>`).join('')}</div><div id="pdf116PerspectiveLayer" class="pdf116-perspective" hidden><svg viewBox="0 0 100 100" preserveAspectRatio="none"><polygon id="pdf116Poly"></polygon></svg>${[0,1,2,3].map(i=>`<b data-i="${i}"></b>`).join('')}</div></div><div id="pdf116Grid" class="pdf116-grid" hidden></div></div></div>
  <div class="status-inline" id="pdf116Status">Open a PDF to begin.</div>
  <div class="pdf116-export"><label>Export<select id="pdf116ExportScope"><option value="all">All</option><option value="selected">Selected</option><option value="even">Even</option><option value="odd">Odd</option><option value="current">Current</option><option value="range">Range</option></select></label><input id="pdf116Range" placeholder="1-3,5"><label>Image<select id="pdf116ImageType"><option value="png">PNG</option><option value="jpeg">JPG</option></select></label><label>N-up<select id="pdf116Nup"><option value="1">1/page</option><option value="2">2/page</option><option value="4">4/page</option><option value="6">6/page</option><option value="9">9/page</option></select></label><button class="ghost-btn" id="pdf116Numbers">Page Numbers: Off</button><button class="primary-btn" id="pdf116ExportPdf">Export PDF</button><button class="ghost-btn" id="pdf116ExportImages">Export Images</button><button class="ghost-btn" id="pdf116Print">Direct Print / N-up</button></div>`;sec.querySelector('.panel')?.appendChild(panel)}
  $('openPdfV116').onclick=()=>{panel.hidden=false;panel.scrollIntoView({behavior:'smooth',block:'start'})};$('pdf116Close').onclick=()=>panel.hidden=true;
  const canvas=$('pdf116Canvas'),shell=$('pdf116Shell'),box=$('pdf116CropBox'),pl=$('pdf116PerspectiveLayer'),grid=$('pdf116Grid');
  let pages=[],current=0,selected=new Set(),gridMode=false,cropMode=false,crop={x:.04,y:.04,w:.92,h:.92},drag=null,perspMode=false,pts=null,pdrag=null,pageNumbers=false;
  const undo=[],redo=[];const status=t=>$('pdf116Status').textContent=t;
  function pageClone(p){return{canvas:cloneCanvas(p.canvas),name:p.name,rotation:p.rotation||0,crop:p.crop?{...p.crop}:null,color:p.color||'original'}}
  function snapshot(){return{pages:pages.map(pageClone),current,selected:[...selected]}}
  function pushHistory(){undo.push(snapshot());if(undo.length>15)undo.shift();redo.length=0}
  function restore(s){pages=s.pages.map(pageClone);current=clamp(s.current,0,Math.max(0,pages.length-1));selected=new Set(s.selected.filter(i=>i<pages.length));if(!selected.size&&pages.length)selected.add(current);cropMode=perspMode=false;box.hidden=pl.hidden=true;renderAll()}
  $('pdf116Undo').onclick=()=>{if(!undo.length)return;redo.push(snapshot());restore(undo.pop());status('Undid last PDF edit.')};$('pdf116Redo').onclick=()=>{if(!redo.length)return;undo.push(snapshot());restore(redo.pop());status('Redid PDF edit.')};
  async function pdfToPages(file){const m=await pdfjs(),pdf=await m.getDocument({data:new Uint8Array(await file.arrayBuffer())}).promise,out=[];for(let n=1;n<=pdf.numPages;n++){const pg=await pdf.getPage(n),vp=pg.getViewport({scale:2}),c=document.createElement('canvas');c.width=Math.ceil(vp.width);c.height=Math.ceil(vp.height);await pg.render({canvasContext:c.getContext('2d'),viewport:vp}).promise;out.push({canvas:c,name:`${file.name} • ${n}`,rotation:0,crop:null,color:'original'})}return out}
  async function imagePages(files){const out=[];for(const f of files){const im=await imgFromFile(f),c=document.createElement('canvas');c.width=im.naturalWidth||im.width;c.height=im.naturalHeight||im.height;c.getContext('2d').drawImage(im,0,0);out.push({canvas:c,name:f.name,rotation:0,crop:null,color:'original'})}return out}
  function indices(mode=$('pdf116Scope').value){if(mode==='current')return pages[current]?[current]:[];if(mode==='selected')return [...selected].sort((a,b)=>a-b);if(mode==='even')return pages.map((_,i)=>i).filter(i=>(i+1)%2===0);if(mode==='odd')return pages.map((_,i)=>i).filter(i=>(i+1)%2===1);return pages.map((_,i)=>i)}
  function parseRange(s){const out=[];String(s||'').split(',').map(x=>x.trim()).filter(Boolean).forEach(part=>{if(part.includes('-')){let[a,b]=part.split('-').map(Number);if(a>b)[a,b]=[b,a];for(let n=a;n<=b;n++)if(n>=1&&n<=pages.length)out.push(n-1)}else{const n=+part;if(n>=1&&n<=pages.length)out.push(n-1)}});return[...new Set(out)]}
  function processed(p,opt={}){let src=p.canvas,c=document.createElement('canvas'),ctx;if(!opt.ignoreRotation&&p.rotation%360){const r=((p.rotation%360)+360)%360;if(r===90||r===270){c.width=src.height;c.height=src.width}else{c.width=src.width;c.height=src.height}ctx=c.getContext('2d');ctx.translate(c.width/2,c.height/2);ctx.rotate(r*Math.PI/180);ctx.drawImage(src,-src.width/2,-src.height/2)}else{c.width=src.width;c.height=src.height;c.getContext('2d').drawImage(src,0,0)}
    if(!opt.ignoreCrop&&p.crop){const r=p.crop,o=document.createElement('canvas');o.width=Math.max(1,Math.round(c.width*r.w));o.height=Math.max(1,Math.round(c.height*r.h));o.getContext('2d').drawImage(c,c.width*r.x,c.height*r.y,c.width*r.w,c.height*r.h,0,0,o.width,o.height);c=o}
    if(!opt.ignoreColor&&p.color&&p.color!=='original'){const x=c.getContext('2d'),d=x.getImageData(0,0,c.width,c.height),a=d.data;if(p.color==='gray'){for(let i=0;i<a.length;i+=4){const g=.299*a[i]+.587*a[i+1]+.114*a[i+2];a[i]=a[i+1]=a[i+2]=g}}else if(p.color==='document'){for(let i=0;i<a.length;i+=4){let g=.299*a[i]+.587*a[i+1]+.114*a[i+2];g=clamp((g-128)*1.45+150,0,255);a[i]=a[i+1]=a[i+2]=g>238?255:g}}else if(p.color==='adaptive'){adaptiveBW(d,c.width,c.height)}x.putImageData(d,0,0)}return c}
  function adaptiveBW(img,w,h){const p=img.data,gray=new Uint8Array(w*h),ii=new Float64Array((w+1)*(h+1));for(let y=0;y<h;y++){let rows=0;for(let x=0;x<w;x++){const k=(y*w+x)*4,g=.299*p[k]+.587*p[k+1]+.114*p[k+2];gray[y*w+x]=g;rows+=g;ii[(y+1)*(w+1)+(x+1)]=ii[y*(w+1)+(x+1)]+rows}}const r=Math.max(8,Math.floor(Math.min(w,h)/60)),C=12;for(let y=0;y<h;y++)for(let x=0;x<w;x++){const x1=Math.max(0,x-r),y1=Math.max(0,y-r),x2=Math.min(w-1,x+r),y2=Math.min(h-1,y+r),sum=ii[(y2+1)*(w+1)+(x2+1)]-ii[y1*(w+1)+(x2+1)]-ii[(y2+1)*(w+1)+x1]+ii[y1*(w+1)+x1],mean=sum/((x2-x1+1)*(y2-y1+1)),v=gray[y*w+x]<mean-C?0:255,k=(y*w+x)*4;p[k]=p[k+1]=p[k+2]=v}}
  function render(){if(!pages.length){canvas.width=canvas.height=0;return}const c=processed(pages[current],cropMode?{ignoreCrop:true}:{});canvas.width=c.width;canvas.height=c.height;canvas.getContext('2d').drawImage(c,0,0);requestAnimationFrame(()=>{renderCrop();renderPerspective()})}
  function thumbCanvas(p){const src=processed(p),c=document.createElement('canvas'),s=Math.min(1,130/src.width);c.width=Math.max(1,Math.round(src.width*s));c.height=Math.max(1,Math.round(src.height*s));c.getContext('2d').drawImage(src,0,0,c.width,c.height);return c}
  function select(i,multi=false){current=i;if(!multi)selected.clear();selected.has(i)&&multi?selected.delete(i):selected.add(i);if(!selected.size)selected.add(i);renderAll()}
  function thumbs(){const w=$('pdf116Thumbs');w.innerHTML='';pages.forEach((p,i)=>{const d=document.createElement('div');d.className='pdf116-thumb'+(i===current?' active':'')+(selected.has(i)?' selected':'');d.draggable=true;d.appendChild(thumbCanvas(p));const s=document.createElement('span');s.textContent=`Page ${i+1}${selected.has(i)?' ✓':''}`;d.appendChild(s);d.onclick=e=>select(i,e.ctrlKey||e.metaKey||e.shiftKey);d.ondragstart=e=>e.dataTransfer.setData('text/plain',String(i));d.ondragover=e=>e.preventDefault();d.ondrop=e=>{e.preventDefault();const from=+e.dataTransfer.getData('text/plain');if(from===i||from<0)return;pushHistory();const [m]=pages.splice(from,1);pages.splice(i,0,m);current=i;selected=new Set([i]);renderAll()};w.appendChild(d)})}
  function renderGrid(){grid.innerHTML='';pages.forEach((p,i)=>{const d=document.createElement('div');d.className='pdf116-grid-item'+(selected.has(i)?' selected':'');d.draggable=true;d.appendChild(thumbCanvas(p));const bar=document.createElement('div');bar.innerHTML=`<span>Page ${i+1}</span><button data-a="rot">↷</button><button data-a="del">🗑</button>`;d.appendChild(bar);d.onclick=e=>{const a=e.target.dataset.a;if(a==='rot'){pushHistory();p.rotation=(p.rotation+90)%360;renderAll();return}if(a==='del'){pushHistory();pages.splice(i,1);current=clamp(current,0,pages.length-1);selected=new Set(pages.length?[current]:[]);renderAll();return}select(i,e.ctrlKey||e.metaKey||e.shiftKey)};d.ondragstart=e=>e.dataTransfer.setData('text/plain',String(i));d.ondragover=e=>e.preventDefault();d.ondrop=e=>{e.preventDefault();const from=+e.dataTransfer.getData('text/plain');pushHistory();const [m]=pages.splice(from,1);pages.splice(i,0,m);current=i;selected=new Set([i]);renderAll()};grid.appendChild(d)})}
  function renderAll(){thumbs();if(gridMode)renderGrid();else render();}
  $('pdf116Open').onchange=async e=>{const f=e.target.files?.[0];if(!f)return;status('Loading PDF…');try{pages=await pdfToPages(f);current=0;selected=new Set(pages.length?[0]:[]);undo.length=redo.length=0;gridMode=false;grid.hidden=true;shell.hidden=false;$('pdf116Pages').textContent='Show All Pages';renderAll();status(`Loaded ${pages.length} page(s).`)}catch(err){console.error(err);status('Could not open this PDF.')}e.target.value=''};
  $('pdf116Pages').onclick=()=>{if(!pages.length)return status('Open a PDF first.');gridMode=!gridMode;grid.hidden=!gridMode;shell.hidden=gridMode;box.hidden=pl.hidden=true;cropMode=perspMode=false;$('pdf116Pages').textContent=gridMode?'Back to Page':'Show All Pages';if(gridMode)renderGrid();else render()};
  [['pdf116SelAll','all'],['pdf116SelEven','even'],['pdf116SelOdd','odd']].forEach(([id,m])=>$(id).onclick=()=>{selected=new Set(indices(m));if(selected.size)current=[...selected][0];renderAll()});$('pdf116SelClear').onclick=()=>{selected=new Set([current]);renderAll()};
  function renderCrop(){if(box.hidden||!canvas.width)return;box.style.left=crop.x*100+'%';box.style.top=crop.y*100+'%';box.style.width=crop.w*100+'%';box.style.height=crop.h*100+'%'}
  const pdfCropMove=e=>{if(!drag||e.pointerId!==drag.id)return;e.preventDefault();const dx=(e.clientX-drag.sx)/drag.w,dy=(e.clientY-drag.sy)/drag.hpx,r={...drag.r},h=drag.handle,min=.02;if(h==='move'){r.x=clamp(drag.r.x+dx,0,1-drag.r.w);r.y=clamp(drag.r.y+dy,0,1-drag.r.h)}else{if(h.includes('w')){const nx=clamp(drag.r.x+dx,0,drag.r.x+drag.r.w-min);r.w=drag.r.w+(drag.r.x-nx);r.x=nx}if(h.includes('e'))r.w=clamp(drag.r.w+dx,min,1-drag.r.x);if(h.includes('n')){const ny=clamp(drag.r.y+dy,0,drag.r.y+drag.r.h-min);r.h=drag.r.h+(drag.r.y-ny);r.y=ny}if(h.includes('s'))r.h=clamp(drag.r.h+dy,min,1-drag.r.y)}crop=r;renderCrop()};
  const pdfCropUp=e=>{if(!drag||e.pointerId!==drag.id)return;drag=null;document.removeEventListener('pointermove',pdfCropMove,true);document.removeEventListener('pointerup',pdfCropUp,true);document.removeEventListener('pointercancel',pdfCropUp,true)};
  box.onpointerdown=e=>{if(e.button!==0)return;e.preventDefault();e.stopPropagation();const rect=shell.getBoundingClientRect();drag={id:e.pointerId,handle:e.target.dataset.h||'move',sx:e.clientX,sy:e.clientY,r:{...crop},w:Math.max(1,rect.width),hpx:Math.max(1,rect.height)};document.addEventListener('pointermove',pdfCropMove,true);document.addEventListener('pointerup',pdfCropUp,true);document.addEventListener('pointercancel',pdfCropUp,true)};
  function enterCrop(r){cropMode=true;perspMode=false;pl.hidden=true;crop=r||{x:.04,y:.04,w:.92,h:.92};box.hidden=false;$('pdf116Crop').textContent='Apply Crop';renderCrop()}
  $('pdf116Crop').onclick=()=>{if(!pages.length)return status('Open a PDF first.');if(!cropMode){enterCrop(pages[current].crop||{x:.04,y:.04,w:.92,h:.92});render();requestAnimationFrame(renderCrop);return;}pushHistory();const idx=indices();idx.forEach(i=>{const p=pages[i],base=processed(p,{ignoreCrop:true,ignoreColor:true}),r={...crop},sx=Math.round(r.x*base.width),sy=Math.round(r.y*base.height),sw=Math.max(1,Math.round(r.w*base.width)),sh=Math.max(1,Math.round(r.h*base.height)),out=document.createElement('canvas');out.width=sw;out.height=sh;out.getContext('2d').drawImage(base,sx,sy,sw,sh,0,0,sw,sh);p.canvas=out;p.rotation=0;p.crop=null;});cropMode=false;box.hidden=true;$('pdf116Crop').textContent='Crop';renderAll();status(`Crop applied permanently to ${idx.length} page(s). Undo is available.`)};
  function jsDetectRect(src){const c=document.createElement('canvas'),max=900,s=Math.min(1,max/Math.max(src.width,src.height));c.width=Math.max(1,Math.round(src.width*s));c.height=Math.max(1,Math.round(src.height*s));c.getContext('2d').drawImage(src,0,0,c.width,c.height);const d=c.getContext('2d').getImageData(0,0,c.width,c.height).data,w=c.width,h=c.height,pts=[[3,3],[w-4,3],[3,h-4],[w-4,h-4]],bg=pts.map(([x,y])=>{const k=(y*w+x)*4;return[d[k],d[k+1],d[k+2]]}),B=bg.reduce((a,b)=>a.map((v,i)=>v+b[i]),[0,0,0]).map(v=>v/bg.length);let minX=w,minY=h,maxX=-1,maxY=-1,count=0;const step=Math.max(1,Math.floor(Math.min(w,h)/700));for(let y=0;y<h;y+=step)for(let x=0;x<w;x+=step){const k=(y*w+x)*4,dist=Math.abs(d[k]-B[0])+Math.abs(d[k+1]-B[1])+Math.abs(d[k+2]-B[2]);if(dist>60){minX=Math.min(minX,x);minY=Math.min(minY,y);maxX=Math.max(maxX,x);maxY=Math.max(maxY,y);count++}}if(maxX<0||count<100)return{x:.02,y:.02,w:.96,h:.96};const pad=Math.max(2,Math.round(Math.min(w,h)*.008));minX=clamp(minX-pad,0,w-1);minY=clamp(minY-pad,0,h-1);maxX=clamp(maxX+pad,1,w);maxY=clamp(maxY+pad,1,h);const r={x:minX/w,y:minY/h,w:(maxX-minX)/w,h:(maxY-minY)/h};if(r.w<.3||r.h<.3||r.w*r.h<.18)return{x:.02,y:.02,w:.96,h:.96};return r}
  $('pdf116AutoCrop').onclick=()=>{if(!pages.length)return status('Open a PDF first.');const base=processed(pages[current],{ignoreCrop:true,ignoreColor:true});let r=null;try{r=jsDetectRect(base)}catch{}enterCrop(r||{x:.02,y:.02,w:.96,h:.96});status('Auto Detect prepared the best document boundary found. Move or resize it freely, then Apply Crop.')};
  function renderPerspective(){if(pl.hidden||!pts)return;$('pdf116Poly').setAttribute('points',pts.map(p=>`${p.x*100},${p.y*100}`).join(' '));pl.querySelectorAll('b').forEach((b,i)=>{b.style.left=pts[i].x*100+'%';b.style.top=pts[i].y*100+'%'})}
  pl.querySelectorAll('b').forEach(b=>{b.onpointerdown=e=>{e.preventDefault();pdrag={id:e.pointerId,i:+b.dataset.i};b.setPointerCapture?.(e.pointerId)};b.onpointermove=e=>{if(!pdrag||pdrag.id!==e.pointerId)return;const r=shell.getBoundingClientRect();pts[pdrag.i]={x:clamp((e.clientX-r.left)/r.width,0,1),y:clamp((e.clientY-r.top)/r.height,0,1)};renderPerspective()};b.onpointerup=b.onpointercancel=()=>pdrag=null});
  $('pdf116Perspective').onclick=async()=>{if(!pages.length)return status('Open a PDF first.');if(!perspMode){perspMode=true;cropMode=false;box.hidden=true;pts=[{x:.04,y:.04},{x:.96,y:.04},{x:.96,y:.96},{x:.04,y:.96}];pl.hidden=false;$('pdf116Perspective').textContent='Apply Perspective';renderPerspective();return}if(typeof cv==='undefined'||!cv.Mat)return status('Perspective engine is still loading. Try again in a moment.');try{pushHistory();const src=processed(pages[current],{ignoreCrop:true,ignoreColor:true}),px=pts.map(p=>({x:p.x*src.width,y:p.y*src.height})),w=Math.max(Math.hypot(px[1].x-px[0].x,px[1].y-px[0].y),Math.hypot(px[2].x-px[3].x,px[2].y-px[3].y)),h=Math.max(Math.hypot(px[3].x-px[0].x,px[3].y-px[0].y),Math.hypot(px[2].x-px[1].x,px[2].y-px[1].y)),sm=cv.imread(src),sp=cv.matFromArray(4,1,cv.CV_32FC2,px.flatMap(p=>[p.x,p.y])),dp=cv.matFromArray(4,1,cv.CV_32FC2,[0,0,w-1,0,w-1,h-1,0,h-1]),M=cv.getPerspectiveTransform(sp,dp),dst=new cv.Mat();cv.warpPerspective(sm,dst,M,new cv.Size(Math.max(1,Math.round(w)),Math.max(1,Math.round(h))),cv.INTER_CUBIC,cv.BORDER_REPLICATE,new cv.Scalar());const o=document.createElement('canvas');cv.imshow(o,dst);[sm,sp,dp,M,dst].forEach(x=>x.delete());pages[current]={...pages[current],canvas:o,rotation:0,crop:null};perspMode=false;pl.hidden=true;$('pdf116Perspective').textContent='Perspective Crop';renderAll();status('Perspective crop applied.')}catch(err){console.error(err);status('Perspective crop failed; original page is preserved by Undo.')}};
  function estimateSkew(src){if(typeof cv==='undefined'||!cv.Mat)return 0;const max=1200,s=Math.min(1,max/Math.max(src.width,src.height)),c=document.createElement('canvas');c.width=Math.round(src.width*s);c.height=Math.round(src.height*s);c.getContext('2d').drawImage(src,0,0,c.width,c.height);const im=cv.imread(c),g=new cv.Mat(),e=new cv.Mat(),lines=new cv.Mat();let angles=[];try{cv.cvtColor(im,g,cv.COLOR_RGBA2GRAY);cv.Canny(g,e,50,150,3);cv.HoughLinesP(e,lines,1,Math.PI/180,80,Math.min(c.width,c.height)*.2,20);for(let i=0;i<lines.rows;i++){const a=lines.intPtr(i,0),ang=Math.atan2(a[3]-a[1],a[2]-a[0])*180/Math.PI;if(Math.abs(ang)<25)angles.push(ang)}if(!angles.length)return 0;angles.sort((a,b)=>a-b);return angles[Math.floor(angles.length/2)]}finally{[im,g,e,lines].forEach(x=>x.delete())}}
  function rotateArbitrary(src,deg){const r=deg*Math.PI/180,s=Math.abs(Math.sin(r)),c=Math.abs(Math.cos(r)),o=document.createElement('canvas');o.width=Math.ceil(src.width*c+src.height*s);o.height=Math.ceil(src.width*s+src.height*c);const x=o.getContext('2d');x.fillStyle='#fff';x.fillRect(0,0,o.width,o.height);x.translate(o.width/2,o.height/2);x.rotate(r);x.drawImage(src,-src.width/2,-src.height/2);return o}
  $('pdf116Deskew').onclick=async()=>{const idx=indices();if(!idx.length)return status('Open a PDF first.');pushHistory();for(const i of idx){const base=processed(pages[i],{ignoreCrop:true,ignoreColor:true,ignoreRotation:true}),a=estimateSkew(base);if(Math.abs(a)>.25)pages[i].canvas=rotateArbitrary(base,-a);pages[i].crop=null;pages[i].rotation=0;try{if(window.Tesseract?.createWorker){/* orientation detection intentionally best-effort */}}catch{}}renderAll();status(`Automatic deskew completed for ${idx.length} page(s).`)};
  async function pdfRemoveBgWhiteCanvas(source,onProgress){
    const blob=await blobOf(source,'image/png',1);
    const mod=await import(/* webpackIgnore: true */ 'https://esm.sh/@imgly/background-removal@1.7.0?bundle');
    const removeBackground=mod.default||mod.removeBackground;if(!removeBackground)throw new Error('AI engine unavailable');
    const result=await removeBackground(blob,{model:'medium',proxyToWorker:false,publicPath:'https://staticimgly.com/@imgly/background-removal-data/1.7.0/dist/',output:{format:'image/png',quality:1},progress:(key,current,total)=>{if(total&&onProgress)onProgress(Math.round(current/total*100))}});
    const cutout=await imgFromFile(result),out=document.createElement('canvas');out.width=source.width;out.height=source.height;
    const x=out.getContext('2d');x.fillStyle='#fff';x.fillRect(0,0,out.width,out.height);x.drawImage(cutout,0,0,out.width,out.height);return out;
  }
  function pdfLocalWhiteBackground(source){
    const c=cloneCanvas(source),x=c.getContext('2d',{willReadFrequently:true}),im=x.getImageData(0,0,c.width,c.height),d=im.data,w=c.width,h=c.height;
    const pts=[[0,0],[w-1,0],[0,h-1],[w-1,h-1],[Math.floor(w/2),0],[Math.floor(w/2),h-1],[0,Math.floor(h/2)],[w-1,Math.floor(h/2)]];
    let br=0,bg=0,bb=0;for(const [px,py] of pts){const k=(py*w+px)*4;br+=d[k];bg+=d[k+1];bb+=d[k+2]}br/=pts.length;bg/=pts.length;bb/=pts.length;
    const tol=72,seen=new Uint8Array(w*h),q=[];for(let xx=0;xx<w;xx++){q.push(xx,(h-1)*w+xx)}for(let yy=1;yy<h-1;yy++){q.push(yy*w,yy*w+w-1)}
    let head=0;while(head<q.length){const n=q[head++];if(seen[n])continue;seen[n]=1;const k=n*4,dist=Math.hypot(d[k]-br,d[k+1]-bg,d[k+2]-bb);if(dist>tol)continue;d[k]=d[k+1]=d[k+2]=255;d[k+3]=255;const xx=n%w,yy=(n/w)|0;if(xx)q.push(n-1);if(xx<w-1)q.push(n+1);if(yy)q.push(n-w);if(yy<h-1)q.push(n+w)}
    x.putImageData(im,0,0);return c;
  }
  $('pdf116RemoveBgWhite').onclick=async()=>{
    const idx=indices();if(!idx.length)return status('Open a PDF first.');const btn=$('pdf116RemoveBgWhite'),old=btn.textContent;btn.disabled=true;btn.textContent='Removing…';pushHistory();
    let done=0,usedFallback=0;try{for(const i of idx){const base=processed(pages[i],{ignoreCrop:true,ignoreColor:true});status(`Removing background • page ${i+1} • ${done+1}/${idx.length}`);let out;try{out=await pdfRemoveBgWhiteCanvas(base,p=>status(`Removing background • page ${i+1} • ${p}% • ${done+1}/${idx.length}`))}catch(err){console.warn('PDF AI background removal unavailable; using local fallback.',err);out=pdfLocalWhiteBackground(base);usedFallback++}pages[i].canvas=out;pages[i].rotation=0;pages[i].crop=null;pages[i].color='original';done++;renderAll()}status(`Remove BG + White complete • ${done} page(s)${usedFallback?` • local fallback used on ${usedFallback}`:' • AI'}.`)}catch(err){console.error(err);status(`Background removal stopped after ${done} page(s). Use Undo to restore.`)}finally{btn.disabled=false;btn.textContent=old}
  };
  $('pdf116RotL').onclick=()=>{const idx=indices();if(!idx.length)return;pushHistory();idx.forEach(i=>pages[i].rotation=(pages[i].rotation-90)%360);renderAll()};$('pdf116RotR').onclick=()=>{const idx=indices();if(!idx.length)return;pushHistory();idx.forEach(i=>pages[i].rotation=(pages[i].rotation+90)%360);renderAll()};
  $('pdf116Color').onchange=e=>{const idx=indices();if(!idx.length)return;pushHistory();idx.forEach(i=>pages[i].color=e.target.value);renderAll()};
  $('pdf116Delete').onclick=()=>{const idx=indices();if(!idx.length)return;pushHistory();[...idx].sort((a,b)=>b-a).forEach(i=>pages.splice(i,1));current=clamp(current,0,Math.max(0,pages.length-1));selected=new Set(pages.length?[current]:[]);renderAll()};
  $('pdf116Blank').onclick=()=>{pushHistory();const ref=pages[current]?.canvas,c=document.createElement('canvas');c.width=ref?.width||1240;c.height=ref?.height||1754;const x=c.getContext('2d');x.fillStyle='#fff';x.fillRect(0,0,c.width,c.height);const at=pages.length?current+1:0;pages.splice(at,0,{canvas:c,name:'Blank page',rotation:0,crop:null,color:'original'});current=at;selected=new Set([at]);renderAll()};
  async function insertList(add){if(!add.length)return;pushHistory();const at=pages.length?current+1:0;pages.splice(at,0,...add);current=at;selected=new Set(add.map((_,j)=>at+j));renderAll()}
  $('pdf116AddPdf').onchange=async e=>{const f=e.target.files?.[0];if(f)await insertList(await pdfToPages(f));e.target.value=''};$('pdf116AddImage').onchange=async e=>{if(e.target.files?.length)await insertList(await imagePages([...e.target.files]));e.target.value=''};
  $('pdf116Replace').onchange=async e=>{const f=e.target.files?.[0];if(!f||!pages.length)return;let add;if(/pdf$/i.test(f.type)||/\.pdf$/i.test(f.name))add=await pdfToPages(f);else add=await imagePages([f]);if(add.length){pushHistory();pages.splice(current,1,...add);selected=new Set(add.map((_,j)=>current+j));renderAll()}e.target.value=''};
  $('pdf116Scanner').onclick=async()=>{if(!S.scanImg)return status('No scanner page is currently available. Scan or upload a page in Scanner first.');const im=S.scanImg,c=document.createElement('canvas');c.width=im.naturalWidth||im.width;c.height=im.naturalHeight||im.height;c.getContext('2d').drawImage(im,0,0);insertList([{canvas:c,name:'Scanner page',rotation:0,crop:null,color:'original'}])};
  function exportIdx(){const m=$('pdf116ExportScope').value;return m==='range'?parseRange($('pdf116Range').value):indices(m)}
  $('pdf116Numbers').onclick=()=>{pageNumbers=!pageNumbers;$('pdf116Numbers').textContent=`Page Numbers: ${pageNumbers?'On':'Off'}`};
  $('pdf116ExportPdf').onclick=async()=>{const idx=exportIdx();if(!idx.length)return status('No pages selected for export.');status('Exporting PDF…');try{const doc=await PDFLib.PDFDocument.create(),font=pageNumbers?await doc.embedFont(PDFLib.StandardFonts.Helvetica):null;for(let k=0;k<idx.length;k++){const out=processed(pages[idx[k]]),b=await blobOf(out,'image/jpeg',.94),im=await doc.embedJpg(await b.arrayBuffer()),pg=doc.addPage([im.width,im.height]);pg.drawImage(im,{x:0,y:0,width:im.width,height:im.height});if(pageNumbers)pg.drawText(String(k+1),{x:pg.getWidth()/2-4,y:12,size:11,font,color:PDFLib.rgb(.1,.1,.1)})}download(new Blob([await doc.save({useObjectStreams:true})],{type:'application/pdf'}),'advanced-pdf-export.pdf');status(`Exported ${idx.length} page(s).`)}catch(err){console.error(err);status('PDF export failed.')}};
  $('pdf116ExportImages').onclick=async()=>{const idx=exportIdx();if(!idx.length)return status('No pages selected for export.');const jpg=$('pdf116ImageType').value==='jpeg',type=jpg?'image/jpeg':'image/png',ext=jpg?'jpg':'png';status('Exporting images…');if(idx.length===1)return download(await blobOf(processed(pages[idx[0]]),type,.94),`page-${idx[0]+1}.${ext}`);if(window.JSZip){const z=new JSZip();for(const i of idx)z.file(`page-${i+1}.${ext}`,await blobOf(processed(pages[i]),type,.94));download(await z.generateAsync({type:'blob'}),`pdf-pages-${ext}.zip`)}else for(const i of idx)download(await blobOf(processed(pages[i]),type,.94),`page-${i+1}.${ext}`);status(`Exported ${idx.length} image(s).`)};
  function nupSheets(idx,n){const W=2480,H=3508,cols=n===1?1:n===2?1:n===4?2:n===6?2:3,rows=Math.ceil(n/cols),gap=35,m=70,cw=(W-2*m-(cols-1)*gap)/cols,ch=(H-2*m-(rows-1)*gap)/rows,out=[];for(let s=0;s<idx.length;s+=n){const c=document.createElement('canvas');c.width=W;c.height=H;const x=c.getContext('2d');x.fillStyle='#fff';x.fillRect(0,0,W,H);idx.slice(s,s+n).forEach((pi,j)=>{const p=processed(pages[pi]),scale=Math.min(cw/p.width,ch/p.height),dw=p.width*scale,dh=p.height*scale,col=j%cols,row=Math.floor(j/cols),dx=m+col*(cw+gap)+(cw-dw)/2,dy=m+row*(ch+gap)+(ch-dh)/2;x.drawImage(p,dx,dy,dw,dh)});out.push(c)}return out}
  $('pdf116Print').onclick=()=>{const idx=exportIdx();if(!idx.length)return status('No pages selected for printing.');const n=+$('pdf116Nup').value||1,sheets=nupSheets(idx,n),w=open('','_blank');if(!w)return;w.document.write('<html><head><title>PDF Print</title><style>@page{size:A4;margin:0}body{margin:0}.p{page-break-after:always;width:210mm;height:297mm;display:flex;align-items:center;justify-content:center}.p:last-child{page-break-after:auto}img{width:100%;height:100%;object-fit:contain}</style></head><body>'+sheets.map(c=>`<div class="p"><img src="${c.toDataURL('image/jpeg',.94)}"></div>`).join('')+'<script>onload=()=>{print();setTimeout(()=>close(),700)}<\/script></body></html>');w.document.close()};
  window.addEventListener('resize',()=>{renderCrop();renderPerspective()});
}

function start(){removeSmartCrop();installPassportSheet();installPrintStudioPro();installPdfStudio();document.title='Shop Studio Pro v11.7';const bs=document.querySelector('.brand-subtitle');if(bs)bs.textContent='PRO TOOLKIT • V11.7';}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',()=>setTimeout(start,0));else setTimeout(start,0);
})();
